# Generated by Django 3.1.7 on 2021-03-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('subject_uz', models.CharField(max_length=100)),
                ('subject_ru', models.CharField(max_length=100)),
                ('content_uz', models.TextField(blank=True)),
                ('content_ru', models.TextField(blank=True)),
                ('photo', models.ImageField(max_length=255, upload_to='')),
                ('status', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('created_ad', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created_ad', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=45)),
                ('name_ru', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name_uz', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
                ('content_uz', models.CharField(max_length=45)),
                ('content_ru', models.CharField(max_length=45)),
                ('anons_uz', models.CharField(max_length=50)),
                ('anons_ru', models.CharField(max_length=45)),
                ('price', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discount_percent', models.SmallIntegerField(blank=True)),
                ('discount_start', models.DateTimeField()),
                ('discount_end', models.DateTimeField()),
                ('vendor_code', models.CharField(max_length=15)),
                ('photo0', models.ImageField(max_length=255, upload_to='')),
                ('photo1', models.ImageField(max_length=255, upload_to='')),
                ('photo2', models.ImageField(max_length=255, upload_to='')),
                ('created_ad', models.DateTimeField()),
                ('updated_ad', models.DateTimeField()),
                ('availability_unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cabinet.unit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cabinet.category')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cabinet.post')),
            ],
        ),
    ]
